// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQms4MiBVNy7uHq8fgDCVU_KwuSx7fwTc',
    appId: '1:192454870213:web:7a7ba278cd51a1abcf1cac',
    messagingSenderId: '192454870213',
    projectId: 'metro-station-3bcfe',
    authDomain: 'metro-station-3bcfe.firebaseapp.com',
    storageBucket: 'metro-station-3bcfe.appspot.com',
    measurementId: 'G-SPPKZXGDW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ3T4vw3L7zLu8NG9F8RVcyZGif6x7u-Q',
    appId: '1:192454870213:android:e6c8b6d89d8cebeccf1cac',
    messagingSenderId: '192454870213',
    projectId: 'metro-station-3bcfe',
    storageBucket: 'metro-station-3bcfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB86vjKiJrOm1a5XICd2DJ2eaAwOkkzYeU',
    appId: '1:192454870213:ios:1884abe3ebe048f4cf1cac',
    messagingSenderId: '192454870213',
    projectId: 'metro-station-3bcfe',
    storageBucket: 'metro-station-3bcfe.appspot.com',
    iosBundleId: 'com.example.metroStation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB86vjKiJrOm1a5XICd2DJ2eaAwOkkzYeU',
    appId: '1:192454870213:ios:1884abe3ebe048f4cf1cac',
    messagingSenderId: '192454870213',
    projectId: 'metro-station-3bcfe',
    storageBucket: 'metro-station-3bcfe.appspot.com',
    iosBundleId: 'com.example.metroStation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQms4MiBVNy7uHq8fgDCVU_KwuSx7fwTc',
    appId: '1:192454870213:web:1effafb8e2423655cf1cac',
    messagingSenderId: '192454870213',
    projectId: 'metro-station-3bcfe',
    authDomain: 'metro-station-3bcfe.firebaseapp.com',
    storageBucket: 'metro-station-3bcfe.appspot.com',
    measurementId: 'G-Q1RKYT8T86',
  );
}
